apiVersion: v1
kind: Service
metadata:
  labels:
    app: ossm-frontend
  name: ossm-frontend
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ossm-frontend
